POINT_TYPE_CONVERGE = "Converge"
POINT_TYPE_DIVERGE = "Diverge"

GRID_SIZE_X = 15
GRID_SIZE_Y = 15

POINT_STATE_UNDEFINED = 0
POINT_STATE_STRAIGHT = 1
POINT_STATS_TURNOUT = 2

ROUTE_STATE_DEFAULT = 0
ROUTE_STATE_BLOCKED = 1
ROUTE_STATE_ACTIVE = 2