POINT_TYPE_CONVERGE = "Converge"
POINT_TYPE_DIVERGE = "Diverge"

GRID_SIZE_X = 15
GRID_SIZE_Y = 15

POINT_STATE_UNDEFINED = 0
POINT_STATE_STRAIGHT = 1
POINT_STATE_TURNOUT = 2

ROUTE_STATE_DEFAULT = 0
ROUTE_STATE_BLOCKED = 1
ROUTE_STATE_ACTIVE = 2

COLOUR_DEFAULT = "#000000"

ROUTE_COLOUR_SCHEMES = {
	"Red": {
		ROUTE_STATE_DEFAULT: "#FF0000",
		ROUTE_STATE_BLOCKED: "#FF6666",
		ROUTE_STATE_ACTIVE: "#660000"
	},
	"Green": {
		ROUTE_STATE_DEFAULT: "#00FF00",
		ROUTE_STATE_BLOCKED: "#66FF66",
		ROUTE_STATE_ACTIVE: "#006600"
	},
	"Blue": {
		ROUTE_STATE_DEFAULT: "#0000FF",
		ROUTE_STATE_BLOCKED: "#6666FF",
		ROUTE_STATE_ACTIVE: "#000066"
	}
}